### ISSUE TITLE
Failing cases not caught still, debug does not work

### ISSUE THREAD

**Issue by asciifaceman** [naftulikay/ansible-role-degoss#35]
17:36 $ ansible --version
ansible 2.7.0

example role defaults:
```
---
sslRootDir: /etc/ssl
ssls:
  - name: star.domain.com
    bundle: bundle.crt
    key: some.key
    owner: root
```

example role main.yml:

```
---
- name: Make sure SSL directory exists
  become: true
  file:
    path: "{{ sslRootDir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Make individual certificate directories
  become: true
  file:
    path: "{{ sslRootDir }}/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ ssls }}"

- name: Install certificate bundles
  become: true
  copy:
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    src: "{{ item.name }}/{{ item.bundle }}"
    dest: "{{ sslRootDir }}/{{ item.name }}/{{ item.bundle }}"
    backup: yes
  loop: "{{ ssls }}"

- name: Install signing keys
  become: true
  copy:
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    src: "{{ item.name }}/{{ item.key }}"
    dest: "{{ sslRootDir }}/{{ item.name }}/{{ item.key }}"
    backup: yes
  loop: "{{ ssls }}"
```

just throw some files with the names `bundle.crt` and `some.key` in files/ for testing

goss.yml:
```
file:
  /etc/ssl:
    exists: true
    mode: "0755"
    owner: root
    group: root
    filetype: directory
  {{range .Env.ssls}}
  /etc/ssl/{{.name}}:
    exists: false
  /etc/ssl/{{.name}}/{{.bundle}}:
    exists: false
  /etc/ssl/{{.name}}/{{.key}}:
    exists: false
  {{end}}
```

These three tests fail on command line as expected:

```
File: /etc/ssl/star.domain.com/some.key: exists:
Expected
    <bool>: true
to equal
    <bool>: false
```

But degoss glosses right over:

```
TASK [degoss : deploy test files] **********************************************
ok: [default] => (item=tests/goss/goss.yml)

TASK [degoss : run tests] ******************************************************
ok: [default]

TASK [degoss : clean] **********************************************************
skipping: [default]

TASK [degoss : report errors] **************************************************
skipping: [default]

TASK [degoss : report module errors] *******************************************
skipping: [default]

PLAY RECAP *********************************************************************
default                    : ok=20   changed=6    unreachable=0    failed=0
```

Called:

```
- name: Run goss tests
  hosts: all
  roles:
    - role: degoss
      degoss_debug: true
      degoss_clean: false
      goss_file: tests/goss/goss.yml
      goss_env_vars:
        ssls: ssls
```
