### ISSUE TITLE
Can't write variables into test templates

### ISSUE THREAD

**Issue by asciifaceman** [naftulikay/ansible-role-degoss#52]
It doesn't appear goss templates are taking in variables set anywhere, whether facts or direct

Goss call in playbook
```
    - role: degoss
      goss_file: tests/goss/install.yml
      vars:
          somevar: hostname
      goss_variables:
          somevar: hostname
```

tests/goss/install.yml
```
command:
  version:
    exit-status: 0
    exec: "{{ somevar }}"
```

```
Goss Execution Failed (Unable to run tests) (rc=1)
  2020/03/04 23:45:28 template: goss:16: function "somevar" not defined
```
